from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('overall_setupscreen/', views.overall_setupscreen, name='overallsetupscreen'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.user_login, name='user_login'),
    path('customerregistrations/', views.customerregistrations_list, name='customerregistrations_list'),
    path('customerregistrations/<int:pk>/', views.customerregistrations_detail, name='customerregistrations_detail'),
    path('customerregistrations/new/', views.customerregistrations_create, name='customerregistrations_create'),
    path('customerregistrations/<int:pk>/edit/', views.customerregistrations_update, name='customerregistrations_update'),
    path('customerregistrations/<int:pk>/delete/', views.customerregistrations_delete, name='customerregistrations_delete'),
    path('itemcategorymaster/', views.itemcategorymaster_list, name='itemcategorymaster_list'),
    path('itemcategorymaster/<int:pk>/', views.itemcategorymaster_detail, name='itemcategorymaster_detail'),
    path('itemcategorymaster/new/', views.itemcategorymaster_create, name='itemcategorymaster_create'),
    path('itemcategorymaster/<int:pk>/edit/', views.itemcategorymaster_update, name='itemcategorymaster_update'),
    path('itemcategorymaster/<int:pk>/delete/', views.itemcategorymaster_delete, name='itemcategorymaster_delete'),
    path('unitofmeasure/', views.unitofmeasure_list, name='unitofmeasure_list'),
    path('unitofmeasure/<int:pk>/', views.unitofmeasure_detail, name='unitofmeasure_detail'),
    path('unitofmeasure/new/', views.unitofmeasure_create, name='unitofmeasure_create'),
    path('unitofmeasure/<int:pk>/edit/', views.unitofmeasure_update, name='unitofmeasure_update'),
    path('unitofmeasure/<int:pk>/delete/', views.unitofmeasure_delete, name='unitofmeasure_delete'),
    path('branch/', views.supplier_list, name='supplier_list'),
    path('branch/<int:pk>/', views.supplier_detail, name='supplier_detail'),
    path('branch/new/', views.supplier_create, name='supplier_create'),
    path('branch/<int:pk>/edit/', views.supplier_update, name='supplier_update'),
    path('branch/<int:pk>/delete/', views.supplier_delete, name='supplier_delete'),

    path('api/companies/', views.CompanyCreateAPIView.as_view(), name='company-create'),
    path('api/user-subscription/', views.UserSubscriptionAPIView.as_view(), name='user-subscription'),
    path('api/notify/', views.NotifyExpiredview.as_view(), name='notify-subscription'),


    path('countrymaster/', views.countrymaster_list, name='countrymaster_list'),
    path('countrymaster/<int:pk>/', views.countrymaster_detail, name='countrymaster_detail'),
    path('countrymaster/new/', views.countrymaster_create, name='countrymaster_create'),
    path('countrymaster/<int:pk>/edit/', views.countrymaster_update, name='countrymaster_update'),
    path('countrymaster/<int:pk>/delete/', views.countrymaster_delete, name='countrymaster_delete'),
    path('logisticspartner/', views.logisticspartner_list, name='logisticspartner_list'),
    path('logisticspartner/<int:pk>/', views.logisticspartner_detail, name='logisticspartner_detail'),
    path('logisticspartner/new/', views.logisticspartner_create, name='logisticspartner_create'),
    path('logisticspartner/<int:pk>/edit/', views.logisticspartner_update, name='logisticspartner_update'),
    path('logisticspartner/<int:pk>/delete/', views.logisticspartner_delete, name='logisticspartner_delete'),
    path('brandmaster/', views.brandmaster_list, name='brandmaster_list'),
    path('brandmaster/<int:pk>/', views.brandmaster_detail, name='brandmaster_detail'),
    path('brandmaster/new/', views.brandmaster_create, name='brandmaster_create'),
    path('brandmaster/<int:pk>/edit/', views.brandmaster_update, name='brandmaster_update'),
    path('brandmaster/<int:pk>/delete/', views.brandmaster_delete, name='brandmaster_delete'),
    path('storetypemaster/', views.storetypemaster_list, name='storetypemaster_list'),
    path('storetypemaster/<int:pk>/', views.storetypemaster_detail, name='storetypemaster_detail'),
    path('storetypemaster/new/', views.storetypemaster_create, name='storetypemaster_create'),
    path('storetypemaster/<int:pk>/edit/', views.storetypemaster_update, name='storetypemaster_update'),
    path('storetypemaster/<int:pk>/delete/', views.storetypemaster_delete, name='storetypemaster_delete'),
    path('customerstore/', views.customerstore_list, name='customerstore_list'),
    path('customerstore/<int:pk>/', views.customerstore_detail, name='customerstore_detail'),
    path('customerstore/new/', views.customerstore_create, name='customerstore_create'),
    path('customerstore/<int:pk>/edit/', views.customerstore_update, name='customerstore_update'),
    path('customerstore/<int:pk>/delete/', views.customerstore_delete, name='customerstore_delete'),
    path('itemsubcategorymaster/', views.itemsubcategorymaster_list, name='itemsubcategorymaster_list'),
    path('itemsubcategorymaster/<int:pk>/', views.itemsubcategorymaster_detail, name='itemsubcategorymaster_detail'),
    path('itemsubcategorymaster/new/', views.itemsubcategorymaster_create, name='itemsubcategorymaster_create'),
    path('itemsubcategorymaster/<int:pk>/edit/', views.itemsubcategorymaster_update, name='itemsubcategorymaster_update'),
    path('itemsubcategorymaster/<int:pk>/delete/', views.itemsubcategorymaster_delete, name='itemsubcategorymaster_delete'),
    path('suppliercustomermapping/', views.suppliercustomermapping_list, name='suppliercustomermapping_list'),
    path('suppliercustomermapping/<int:pk>/', views.suppliercustomermapping_detail, name='suppliercustomermapping_detail'),
    path('suppliercustomermapping/new/', views.suppliercustomermapping_create, name='suppliercustomermapping_create'),
    path('suppliercustomermapping/<int:pk>/edit/', views.suppliercustomermapping_update, name='suppliercustomermapping_update'),
    path('suppliercustomermapping/<int:pk>/delete/', views.suppliercustomermapping_delete, name='suppliercustomermapping_delete'),
    path('manufacturer/', views.manufacturer_list, name='manufacturer_list'),
    path('manufacturer/<int:pk>/', views.manufacturer_detail, name='manufacturer_detail'),
    path('manufacturer/new/', views.manufacturer_create, name='manufacturer_create'),
    path('manufacturer/<int:pk>/edit/', views.manufacturer_update, name='manufacturer_update'),
    path('manufacturer/<int:pk>/delete/', views.manufacturer_delete, name='manufacturer_delete'),
    path('subcountrymaster/', views.subcountrymaster_list, name='subcountrymaster_list'),
    path('subcountrymaster/<int:pk>/', views.subcountrymaster_detail, name='subcountrymaster_detail'),
    path('subcountrymaster/new/', views.subcountrymaster_create, name='subcountrymaster_create'),
    path('subcountrymaster/<int:pk>/edit/', views.subcountrymaster_update, name='subcountrymaster_update'),
    path('subcountrymaster/<int:pk>/delete/', views.subcountrymaster_delete, name='subcountrymaster_delete'),
    path('Branchstore/', views.supplierstore_list, name='supplierstore_list'),
    path('Branchstore/<int:pk>/', views.supplierstore_detail, name='supplierstore_detail'),
    path('Branchstore/new/', views.supplierstore_create, name='supplierstore_create'),
    path('Branchstore/<int:pk>/edit/', views.supplierstore_update, name='supplierstore_update'),
    path('Branchstore/<int:pk>/delete/', views.supplierstore_delete, name='supplierstore_delete'),
    path('itemmaster/', views.itemmaster_list, name='itemmaster_list'),
    path('itemmaster/<int:pk>/', views.itemmaster_detail, name='itemmaster_detail'),
    path('itemmaster/new/', views.itemmaster_create, name='itemmaster_create'),
    path('itemmaster/<int:pk>/edit/', views.itemmaster_update, name='itemmaster_update'),
    path('itemmaster/<int:pk>/delete/', views.itemmaster_delete, name='itemmaster_delete'),
    path('orderrequestparent/', views.orderrequestparent_list, name='orderrequestparent_list'),
    path('orderrequestparent/<int:pk>/', views.orderrequestparent_detail, name='orderrequestparent_detail'),
    path('orderrequestparent/new/', views.orderrequestparent_create, name='orderrequestparent_create'),
    path('orderrequestparent/<int:pk>/edit/', views.orderrequestparent_update, name='orderrequestparent_update'),
    path('orderrequestparent/<int:pk>/delete/', views.orderrequestparent_delete, name='orderrequestparent_delete'),
    path('stocktransferroutemain/', views.stocktransferroutemain_list, name='stocktransferroutemain_list'),
    path('stocktransferroutemain/<int:pk>/', views.stocktransferroutemain_detail, name='stocktransferroutemain_detail'),
    path('stocktransferroutemain/new/', views.stocktransferroutemain_create, name='stocktransferroutemain_create'),
    path('stocktransferroutemain/<int:pk>/edit/', views.stocktransferroutemain_update, name='stocktransferroutemain_update'),
    path('stocktransferroutemain/<int:pk>/delete/', views.stocktransferroutemain_delete, name='stocktransferroutemain_delete'),
    path('itemunit/', views.itemunit_list, name='itemunit_list'),
    path('itemunit/<int:pk>/', views.itemunit_detail, name='itemunit_detail'),
    path('itemunit/new/', views.itemunit_create, name='itemunit_create'),
    path('itemunit/<int:pk>/edit/', views.itemunit_update, name='itemunit_update'),
    path('itemunit/<int:pk>/delete/', views.itemunit_delete, name='itemunit_delete'),
    path('invoice/', views.invoice_list, name='invoice_list'),
    path('invoice/<int:pk>/', views.invoice_detail, name='invoice_detail'),
    path('invoice/new/', views.invoice_create, name='invoice_create'),
    path('invoice/<int:pk>/edit/', views.invoice_update, name='invoice_update'),
    path('invoice/<int:pk>/delete/', views.invoice_delete, name='invoice_delete'),
    path('stocktransferparent/', views.stocktransferparent_list, name='stocktransferparent_list'),
    path('stocktransferparent/<int:pk>/', views.stocktransferparent_detail, name='stocktransferparent_detail'),
    path('stocktransferparent/new/', views.stocktransferparent_create, name='stocktransferparent_create'),
    path('stocktransferparent/<int:pk>/edit/', views.stocktransferparent_update, name='stocktransferparent_update'),
    path('stocktransferparent/<int:pk>/delete/', views.stocktransferparent_delete, name='stocktransferparent_delete'),
    path('stocktransferroutesub/', views.stocktransferroutesub_list, name='stocktransferroutesub_list'),
    path('stocktransferroutesub/<int:pk>/', views.stocktransferroutesub_detail, name='stocktransferroutesub_detail'),
    path('stocktransferroutesub/new/', views.stocktransferroutesub_create, name='stocktransferroutesub_create'),
    path('stocktransferroutesub/<int:pk>/edit/', views.stocktransferroutesub_update, name='stocktransferroutesub_update'),
    path('stocktransferroutesub/<int:pk>/delete/', views.stocktransferroutesub_delete, name='stocktransferroutesub_delete'),
    path('packagesizemaster/', views.packagesizemaster_list, name='packagesizemaster_list'),
    path('packagesizemaster/<int:pk>/', views.packagesizemaster_detail, name='packagesizemaster_detail'),
    path('packagesizemaster/new/', views.packagesizemaster_create, name='packagesizemaster_create'),
    path('packagesizemaster/<int:pk>/edit/', views.packagesizemaster_update, name='packagesizemaster_update'),
    path('packagesizemaster/<int:pk>/delete/', views.packagesizemaster_delete, name='packagesizemaster_delete'),
    path('packageassignment/', views.packageassignment_list, name='packageassignment_list'),
    path('packageassignment/<int:pk>/', views.packageassignment_detail, name='packageassignment_detail'),
    path('packageassignment/new/', views.packageassignment_create, name='packageassignment_create'),
    path('packageassignment/<int:pk>/edit/', views.packageassignment_update, name='packageassignment_update'),
    path('packageassignment/<int:pk>/delete/', views.packageassignment_delete, name='packageassignment_delete'),
    path('orderrequestchild/', views.orderrequestchild_list, name='orderrequestchild_list'),
    path('orderrequestchild/<int:pk>/', views.orderrequestchild_detail, name='orderrequestchild_detail'),
    path('orderrequestchild/new/', views.orderrequestchild_create, name='orderrequestchild_create'),
    path('orderrequestchild/<int:pk>/edit/', views.orderrequestchild_update, name='orderrequestchild_update'),
    path('orderrequestchild/<int:pk>/delete/', views.orderrequestchild_delete, name='orderrequestchild_delete'),
    path('manualstockadjustment/', views.manualstockadjustment_list, name='manualstockadjustment_list'),
    path('manualstockadjustment/<int:pk>/', views.manualstockadjustment_detail, name='manualstockadjustment_detail'),
    path('manualstockadjustment/new/', views.manualstockadjustment_create, name='manualstockadjustment_create'),
    path('manualstockadjustment/<int:pk>/edit/', views.manualstockadjustment_update, name='manualstockadjustment_update'),
    path('manualstockadjustment/<int:pk>/delete/', views.manualstockadjustment_delete, name='manualstockadjustment_delete'),
    path('stocktransferchild/', views.stocktransferchild_list, name='stocktransferchild_list'),
    path('stocktransferchild/<int:pk>/', views.stocktransferchild_detail, name='stocktransferchild_detail'),
    path('stocktransferchild/new/', views.stocktransferchild_create, name='stocktransferchild_create'),
    path('stocktransferchild/<int:pk>/edit/', views.stocktransferchild_update, name='stocktransferchild_update'),
    path('stocktransferchild/<int:pk>/delete/', views.stocktransferchild_delete, name='stocktransferchild_delete'),

    #----------------------------------------------------
    path('supplierapproval/', views.supplier_approval, name='supplier_approval'),
    path('approval/<int:id>/', views.approval, name='approval'),
    path('rejection/', views.rejection, name='rejection'),
    path('customerapproval/', views.customer_approval, name='customer_approval'),
    path('customerapproval/<int:id>/', views.customer_admin_approval, name='customer_admin_approval'),
    path('customerrejection/', views.customer_rejection, name='customer_rejection'),
    path('get-subcategories/', views.get_subcategories, name='get_subcategories'),

    path('producttype/', views.producttype_list, name='producttype_list'),
    path('producttype/<int:pk>/', views.producttype_detail, name='producttype_detail'),
    path('producttype/new/', views.producttype_create, name='producttype_create'),
    path('producttype/<int:pk>/edit/', views.producttype_update, name='producttype_update'),
    path('producttype/<int:pk>/delete/', views.producttype_delete, name='producttype_delete'),

    path('invite/', views.invite, name='invite'),
    path('vendor/', views.Vendor_list, name='Vendor_list'),
    path('vendor/<int:pk>/', views.vendor_detail, name='vendor_detail'),
    path('vendor/new/', views.vendor_create, name='vendor_create'),
    path('vendor/<int:pk>/edit/', views.vendor_update, name='vendor_update'),
    path('vendor/<int:pk>/delete/', views.vendor_delete, name='vendor_delete'),

    
    

    path("root-mapping/<int:pk>/", views.root_mapping, name="rootmapping"),
    path('get-mapped-customers/', views.get_mapped_customers, name='get_mapped_customers'),
    path('get-customer-stores/', views.get_customer_stores, name='get_customer_stores'),
    path('disply-allsupplier/', views.disply_allsupplier, name='disply_allsupplier'),
    path("disply-routes/<int:pk>/", views.disply_routes, name="disply_routes"),
    path("disply-routesdetailed/<int:pk>/", views.disply_routesdetailed, name="displyroutesdetailed"),
    path('distributor_apporovallist/', views.distributor_apporovallist, name='distributor_apporovallist'),
    path('create_distributor_branch/<int:id>/', views.create_distributor_branch, name='create_distributor_branch'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    
    path('logistics_list',views.logistics_list,name="logistics_list"),
    path('assign_logisticsvehicles/<int:pk>/', views.assign_logisticsvehicles, name='assignlogisticsvehicles'),
    path('multiapproval_process/', views.multiapproval_process, name='multiapproval_process'),
    path('multiapproval_view/', views.multiapproval_view, name='multiapprovalview'),
    path("multiapproval_delete/<int:pk>/", views.multiapproval_delete, name="multiapproval_delete"),



]