from django.urls import path
from SupplierPortal import DeepakView, reports, stockadjust, stocktransferview, views
from SupplierPortal import supplierusers as viewss
from SupplierPortal import reports as view1
urlpatterns = [
    path('supplierdashboard/', views.supplierdashboard, name='supplierdashboard'),
    path('supplierorder/', views.supplierorder, name='supplierorder'),
    path('supplieroredr_itemstemp/', views.supplieroredr_itemstemp, name='supplieroredritemstemp'),
    path('delete_POtempdetails/<int:pk>/', views.delete_POtemp_details, name='delete_POtempdetails'),
    path('supplierorder_view/', views.supplierorder_view, name='supplierorderview'),
    path('approved_orderslist/', views.approved_orderslist, name='approvedorders_list'),
    path('reorder_stocks/', views.reorder_stocks, name='reorder_stocks'),
    path('supplierordersub_view/<int:pk>/', views.supplierordersub_view, name='supplierordersubview'),
    path('supplierorder_preview/<int:pk>/', views.supplierorder_preview, name='supplierorderpreview'),
    path("create_supplier_order/", views.pending_orders, name="create_supplier_order"),
    path("orderlist/<int:id>/", views.orderlist, name="orderlist"),
    path("orderapproval/<int:id>/", views.orderapproval, name="orderapproval"),
    path("order_rejections/<int:id>/", views.order_rejections, name="order_rejections"),
    path('get_package_sizes/', views.get_package_sizes, name='get_package_sizes'),
    path("get-item-price/", views.get_item_price, name="get_item_price"),
    path('po_edit/<int:pk>/',views.po_edit,name='po_edit'),
    path("delete-order-item/", views.delete_order_item, name="delete_order_item"),
    path('po_delete/<int:pk>/',views.po_delete,name='po_delete'),
    path('goodsreceivedfromvendor/', views.goodsreceivedfromvendor, name='goodsreceivedfromvendor'),
    path('goodsreceivedfromvendorSub/<int:pk>/', views.goodsreceivedfromvendorSub, name='goodsreceivedfromvendorSub'),
    path('received_goodsmain_details/', views.received_goodsmain_details, name='received_goodsmain_details'),
    path('received_goodssub_details/<int:pk>/', views.received_goodssub_details, name='received_goodssub_details'),
    path('supplier_grminvoice/<int:pk>/', views.supplier_grminvoice, name='supplier_grminvoice'),
    path('all_goods',views.all_goods, name='all_goods'),
    path('paymentdetails',views.paymentdetails, name='paymentdetails'),
    path('paiddetails/<int:pk>/',views.paiddetails, name='paiddetails'),


    path('pay/<int:id>/', DeepakView.pay, name='pay'),
    # path('payable_amount/<int:id>/', DeepakView.payable_amount, name='payable_amount'),
    
    path('bulk_upload_items/', DeepakView.bulk_upload_items, name='bulk_upload_items'),
    path('bulk_upload_itemcategory_master/', DeepakView.bulk_upload_itemcategory_master, name='bulk_upload_itemcategory_master'),
    path('bulk_upload_subcategory_master/', DeepakView.bulk_upload_subcategory_master, name='bulk_upload_subcategory_master'),
    path('bulk_upload_brand_master/', DeepakView.bulk_upload_brand_master, name='bulk_upload_brand_master'),
    path('bulk_upload_unitofmeasure/', DeepakView.bulk_upload_unitofmeasure, name='bulk_upload_unitofmeasure'),
    path('bulk_upload_itemunit/', DeepakView.bulk_upload_itemunit, name='bulk_upload_itemunit'),
    path('bulk_upload_packagesizemaster/', DeepakView.bulk_upload_packagesizemaster, name='bulk_upload_packagesizemaster'),
    path('bulk_upload_countrymaster/', DeepakView.bulk_upload_countrymaster, name='bulk_upload_countrymaster'),
    path('bulk_upload_subcountrymaster/', DeepakView.bulk_upload_subcountrymaster, name='bulk_upload_subcountrymaster'),
    path('bulk_upload_storetypemaster/', DeepakView.bulk_upload_storetypemaster, name='bulk_upload_storetypemaster'),
    path('create_branch/', DeepakView.create_branch, name='create_branch'),
    path('new_branch_create/', DeepakView.new_branch_create, name='new_branch_create'),
    path('create_storemaster/', DeepakView.create_storemaster, name='create_storemaster'),
    path('new_storemaster_create/', DeepakView.new_storemaster_create, name='new_storemaster_create'),

    path('pending-invoices/', views.pending_invoices, name='pendinginvoices'),
    path('paymentprocess/<int:pk>/', views.paymentprocess, name='paymentprocess'),
    path('create_invoice/', views.create_invoice, name='create_invoice'),
    path('supplier_invoice_edit/<int:pk>', views.supplier_invoice_edit, name='supplierinvoiceedit'),
    path('itemreturn-to-manufacturer/', views.item_return_to_manufacturer, name='itemreturn_to_manufacturer'),
    path('stockreturnto-manufacturer/<int:pk>', views.stockreturnto_manufacturer, name='stockreturnto_manufacturer'),
    path('view_returntomanufacturermain', views.view_returntomanufacturermain, name='viewreturntomanufacturermain'),
    path('view_returntomanufacturersub/<int:pk>', views.view_returntomanufacturersub, name='viewreturntomanufacturersub'),
    path('search-instock-forwastage/', views.search_instock_forwastage, name='search_instock_forwastage'),
    path('save-wastage-stocks/<int:pk>', views.save_wastage_stocks, name='save_wastage_stocks'),
    path('disply-forwastage', views.disply_forwastage, name='displyforwastage'),

    path('Stock-details/', views.Stock_details, name='Stockdetails'),

    path('supplier_dashboard/', views.supplier_dashboard, name='supplier_dashboard'),

    path('supplierrole_list/',viewss.supplierrole_list,name='supplierrolelist'),
    path('supplierrole_create/',viewss.supplierrole_create,name='supplierrolecreate'),
    path('supplierpermission/<int:pk>/',viewss.supplierpermission,name='supplierpermission'),
    path('supplieruser_list/',viewss.supplieruser_list,name='supplieruser_list'),
    path('supplieruser_create/',viewss.supplieruser_create,name='supplierusercreate'),
    path('stocktransfer_dashboard',views.stocktransfer_dashboard,name='stocktransfer_dashboard'),
    
    path('stocktransfer_tostore/',views.stocktransfer_tostore,name='stocktransfertostore'),
    path('disply_transferdetails/',views.disply_transferdetails,name='displytransferdetails'),
    path('transfer_confirmation/<int:pk>/',views.transfer_confirmation,name='transferconfirmation'),
    path('disply_transfer/',views.disply_transfer,name='displytransfer'),
    path('assign_logisticstransfer/<int:pk>/',views.assign_logisticstransfer,name='assignlogisticstransfer'),

    path('supplierstock_transferdetails/',views.supplierstock_transferdetails,name='supplierstocktransferdetailssss'),
    path('stocktransfer_status/<pk>',views.stocktransfer_status,name='_stocktransferstatus'),
    path('delivered_stocks/',views.delivered_stocks,name='delivered_stocks'),
    path('Stockdelivered_confirmation/<int:pk>/',views.Stockdelivered_confirmation,name='stockdelivered_confirmation'),

    #=============== Reports Starts ==================
    
    path('supplierreport_dashboard',view1.supplierreport_dashboard,name='supplierreportdashboard'),
    path('supplierorder_report',view1.supplierorder_report,name='supplierorderreport'),
    path('supplierorder_approval_report',view1.supplierorder_approval_report,name='supplierorderapprovalreport'),
    path('goodsreceive_report',view1.goodsreceive_report,name='goodsreceivereport'),
    path('supplierstock_report',view1.supplierstock_report,name='supplierstock_report'),
    path('invoices_reports',view1.invoices_reports,name='invoices_reports'),
    path('stock_transferreport',view1.stock_transferreport,name='stocktransferreport'),
    path('stock_returnreport',view1.stock_returnreport,name='stock_returnreport'),
    path('stock_wastagereport',view1.stock_wastagereport,name='stock_wastagereport'),
    path('supplierstoretostorerequest_view',views.supplierstoretostorerequest_view,name='supplierstoretostorerequest_view'),
    path('supplierstoretostorerequestsub_view/<int:pk>/',views.supplierstoretostorerequestsub_view,name='supplierstoretostorerequestsub_view'),
    path('stock_request_tostore',views.stock_request_tostore,name='stock_request_tostore'),
    path('supplierstorerequest_itemstemp',views.supplierstorerequest_itemstemp,name='supplierstorerequest_itemstemp'),
    path('supplierstorerequest_itemsdelete/<int:pk>/',views.supplierstorerequest_itemsdelete,name='supplierstorerequestitemsdelete'),
    path('supplierstorerequestapproval/<int:pk>/',views.supplierstorerequestapproval,name='supplierstorerequestapproval'),
    path('supplierstorerequestrejection/<int:pk>/',views.supplierstorerequestrejection,name='supplierstorerequestrejection'),
    path('supplierstorerequest_preview/<int:pk>/',views.supplierstorerequest_preview,name='supplierstorerequest_preview'),
    path('approved_supplierstorerequest',views.approved_supplierstorerequest,name='approvedsupplierstorerequest'),
    path('supplierstorerequest_transfer/<int:pk>/',views.supplierstorerequest_transfer,name='supplierstorerequesttransfer'),
    path('get_batch_data/', views.get_batch_data, name='get_batch_data'),
    path('view_supplierstorerequest/', stocktransferview.view_supplierstorerequest, name='view_supplierstorerequest'),
    path('direct_suppliertransferdetails/', stocktransferview.direct_suppliertransferdetails, name='direct_suppliertransferdetails'),
    path('direct_suppliertransferdetailssub/<int:id>', stocktransferview.direct_suppliertransferdetailssub, name='direct_suppliertransferdetailssub'),
    path('view_disply_transfer/', stocktransferview.view_disply_transfer, name='view_disply_transfer'),
    path('view_delivered_stocks/', stocktransferview.view_delivered_stocks, name='view_delivered_stocks'),
    path('view_supplierdisply_transferdetails/', stocktransferview.view_supplierdisply_transferdetails, name='view_supplierdisply_transferdetails'),
    path('supplier_view_returntomanufacturermain/', stocktransferview.supplier_view_returntomanufacturermain, name='supplier_view_returntomanufacturermain'),
    path('supplier_returntomanufacturersub/<int:pk>', stocktransferview.supplier_returntomanufacturersub, name='supplier_returntomanufacturersub'),
    path('stocktransferdistributor_dashboard/', views.stocktransferdistributor_dashboard, name='stocktransferdistributordashboard'),
    path('distributor_request/', views.distributor_request, name='distributor_request'),
    path('distributorrequest_transfer/<int:pk>/',views.distributorrequest_transfer,name='distributorrequest_transfer'),
    path('distributor_transfered_view/', views.distributor_transfered_view, name='distributortransfered_view'),
    path('distributor_transfered_sub/<int:pk>/',views.distributor_transfered_sub,name='distributortransferedsub'),
    path('disply_distributortransfer/', views.disply_distributortransfer, name='disply_distributor_transfer'),
    path('distributortransfer_confirmation/<int:pk>/',views.distributortransfer_confirmation,name='distributortransfer_confirmation'),
    path('confirmeddistributor_transfered/', views.confirmeddistributor_transfered, name='confirmeddistributor_transfered'),
    path('assignlogistic_distributortransfer/', views.assignlogistic_distributortransfer, name='assignlogistic_distributortransfer'),
    path('view_suppliertransfer_sub/<pk>',stocktransferview.view_suppliertransfer_sub,name='view_suppliertransfer_sub'),

    path('stockreorder_report',view1.stockreorder_report,name='stockreorder_report'),

    path('supplier_stockadjustment/',stockadjust.supplier_stockadjustment,name='supplier_stockadjustment'),
    path('supplier_viewstockadjust/',stockadjust.supplier_viewstockadjust,name='supplier_viewstockadjust'),
    path('supplier_viewstockadjustsub/<int:id>/',stockadjust.supplier_viewstockadjustsub,name='supplier_viewstockadjustsub'),
    path('manualstock_report/',reports.manualstock_report,name='manualstock_report'),
    path('upload_supplierinventory_csv/',stockadjust.upload_supplierinventory_csv,name='upload_supplierinventory_csv'),
    path('supplier_stockrequest_edit/<int:pk>/',stockadjust.supplier_stockrequest_edit,name='supplier_stockrequest_edit'),
    path('displyownproduct/', views.displyownproduct, name='displyownproduct'),
    path('billofmaterial/<pk>', views.billofmaterial, name='billofmaterial'),
    path('get_itemunitdetails_js/', views.get_itemunitdetails_js, name='get_itemunitdetails_js'),
    path('orderapprovals_view/<pk>', views.orderapprovals_view, name='orderapprovalsview'),
    


]